### ISSUE TITLE
Runner Book Question?

### ISSUE THREAD

**Issue by jsphon** [rozzac90/betdaq#14]
Hi,

Thanks for writing such a great API.

When I get a runner book, such as the one below, what do the first elements (0, 0, 1 below) represent?

`{'batb': [[0, 5.3, 46.51]], 'batl': [[0, 6.6, 60.61], [1, 6.8, 11.0]]}`

**Comment by rozzac90** [comment]
They will be references to that orders position in the orderbook, 0 meaning it is the top of that side of the orderbook.
